# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-alpine

WORKDIR /app

# Copy all files to the container
COPY . /app

# Install dependencies ignoring the Python version requirement
RUN pip install --ignore-requires-python --no-cache-dir .

CMD ["python", "mcp-test.py"]
